// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // =================== WEB ===================
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mtL2LjVdth1MxjEscr6gaS4VIMB7TuA',
    appId: '1:745665858284:web:cdd0634897d4f23a9673c9',
    messagingSenderId: '745665858284',
    projectId: 'sourcesauce-bd4f6',
    authDomain: 'sourcesauce-bd4f6.firebaseapp.com',
    storageBucket: 'sourcesauce-bd4f6.firebasestorage.app',
  );

  // =================== ANDROID ===================
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2mtL2LjVdth1MxjEscr6gaS4VIMB7TuA',
    appId: '1:745665858284:android:cdd0634897d4f23a9673c9',
    messagingSenderId: '745665858284',
    projectId: 'sourcesauce-bd4f6',
    storageBucket: 'sourcesauce-bd4f6.firebasestorage.app',
  );

  // =================== IOS ===================
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2mtL2LjVdth1MxjEscr6gaS4VIMB7TuA',
    appId: '1:745665858284:ios:cdd0634897d4f23a9673c9',
    messagingSenderId: '745665858284',
    projectId: 'sourcesauce-bd4f6',
    storageBucket: 'sourcesauce-bd4f6.firebasestorage.app',
    iosBundleId: 'com.example.flutter_application_1',
  );

  // =================== MACOS ===================
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2mtL2LjVdth1MxjEscr6gaS4VIMB7TuA',
    appId: '1:745665858284:ios:cdd0634897d4f23a9673c9',
    messagingSenderId: '745665858284',
    projectId: 'sourcesauce-bd4f6',
    storageBucket: 'sourcesauce-bd4f6.firebasestorage.app',
    iosBundleId: 'com.example.flutter_application_1',
  );

  // =================== WINDOWS ===================
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2mtL2LjVdth1MxjEscr6gaS4VIMB7TuA',
    appId: '1:745665858284:windows:cdd0634897d4f23a9673c9',
    messagingSenderId: '745665858284',
    projectId: 'sourcesauce-bd4f6',
    authDomain: 'sourcesauce-bd4f6.firebaseapp.com',
    storageBucket: 'sourcesauce-bd4f6.firebasestorage.app',
  );
}
